import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for Coach OS - How we collect, use, and protect your data.',
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-titanium-950 pt-16">
      {/* Content */}
      <article className="py-12">
        <div className="container mx-auto max-w-4xl px-6">
          <h1 className="mb-8 font-serif text-4xl font-bold">Privacy Policy</h1>
          <p className="mb-8 text-silver-dark">Last updated: January 2025</p>

          <div className="prose prose-invert prose-lg max-w-none space-y-8 text-silver-light">
            <section>
              <h2 className="text-2xl font-bold text-white">1. Introduction</h2>
              <p>
                Coach OS ("we", "our", or "us") is operated by Thrive Venture Labs Limited,
                a company registered in England and Wales. We are committed to protecting
                your privacy and handling your data with transparency and care.
              </p>
              <p>
                This Privacy Policy explains how we collect, use, disclose, and safeguard
                your information when you use our AI coaching platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">2. Information We Collect</h2>

              <h3 className="text-xl font-semibold text-silver">Account Information</h3>
              <p>When you create an account, we collect:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Email address</li>
                <li>Name (optional)</li>
                <li>Business context you provide during onboarding</li>
              </ul>

              <h3 className="text-xl font-semibold text-silver">Coaching Data</h3>
              <p>To provide personalised coaching, we store:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Conversation history (voice transcripts and text chats)</li>
                <li>Goals you set within the platform</li>
                <li>Action items extracted from conversations</li>
                <li>Session summaries generated by AI</li>
              </ul>

              <h3 className="text-xl font-semibold text-silver">Usage Data</h3>
              <p>We automatically collect:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Pages visited and features used</li>
                <li>Session duration and frequency</li>
                <li>Device type and browser information</li>
                <li>Approximate location (country/city from IP)</li>
              </ul>

              <h3 className="text-xl font-semibold text-silver">Payment Information</h3>
              <p>
                Payment processing is handled by Revolut. We do not store your full
                payment card details. We receive only the information necessary to
                manage your subscription (e.g., subscription status, billing dates).
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">3. How We Use Your Information</h2>
              <p>We use your information to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Provide AI coaching services with context awareness</li>
                <li>Maintain conversation history for continuity</li>
                <li>Generate session summaries and track your progress</li>
                <li>Process payments and manage subscriptions</li>
                <li>Improve our services and develop new features</li>
                <li>Send service-related communications</li>
                <li>Comply with legal obligations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">4. AI Processing</h2>
              <p>
                Coach OS uses third-party AI services (Google Gemini, OpenAI) to power
                coaching conversations. Your conversation data is sent to these services
                for processing. We have data processing agreements in place with these
                providers.
              </p>
              <p>
                Conversation embeddings are stored locally in our database to enable
                context-aware coaching. These are numerical representations that allow
                the AI to recall relevant past discussions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">5. Data Storage and Security</h2>
              <p>
                Your data is stored securely using Supabase (PostgreSQL database hosted
                on AWS). We implement industry-standard security measures including:
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Encryption in transit (TLS/HTTPS)</li>
                <li>Encryption at rest</li>
                <li>Row-level security policies</li>
                <li>Regular security audits</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">6. Data Retention</h2>
              <p>
                We retain your data for as long as your account is active. If you
                delete your account, we will delete your personal data within 30 days,
                except where we are required to retain it for legal purposes.
              </p>
              <p>
                You can request deletion of specific conversations or all your data
                at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">7. Your Rights</h2>
              <p>Under GDPR and UK data protection law, you have the right to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Access your personal data</li>
                <li>Rectify inaccurate data</li>
                <li>Request deletion of your data</li>
                <li>Object to processing</li>
                <li>Data portability</li>
                <li>Withdraw consent at any time</li>
              </ul>
              <p>
                To exercise these rights, contact us at privacy@ceocoachos.com.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">8. Cookies</h2>
              <p>
                We use essential cookies to maintain your session and preferences.
                We use Vercel Analytics for basic usage statistics, which does not
                use cookies for tracking.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">9. Third-Party Services</h2>
              <p>We use the following third-party services:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Supabase</strong> - Database and authentication</li>
                <li><strong>Vercel</strong> - Hosting and analytics</li>
                <li><strong>Google (Gemini)</strong> - AI processing</li>
                <li><strong>OpenAI</strong> - AI processing and embeddings</li>
                <li><strong>Revolut</strong> - Payment processing</li>
                <li><strong>Resend</strong> - Email delivery</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">10. Changes to This Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. We will notify
                you of any material changes by email or through the platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-white">11. Contact Us</h2>
              <p>
                If you have questions about this Privacy Policy or our data practices,
                please contact us at:
              </p>
              <p>
                <strong>Thrive Venture Labs Limited</strong><br />
                Email: privacy@ceocoachos.com
              </p>
            </section>
          </div>
        </div>
      </article>
    </main>
  )
}
